### ISSUE TITLE
Selector threshold

### ISSUE THREAD

**Issue by RamonGebben** [ryanpcmcquen/scrollEvents#2]
It would be awesome to use as selector as a scroll threshold.

I picture it working like this:

``` javascript
scrollEvents.changeStyle(".foo", "height", "400px", ".bar");
```

**Comment by ryanpcmcquen** [comment]
@RamonGebben I like where you are going with this, so would the selector take the place of the `breakPoint` argument?

**Comment by RamonGebben** [comment]
Yeah then the `breakPoint` would become something like this

``` javascript
document.querySelector(<selector>).offsetTop
```

**Comment by ryanpcmcquen** [comment]
I like this a lot, I will implement something for the upcoming release or the one after that. Would you mind testing some code before a release?

**Comment by ryanpcmcquen** [comment]
@RamonGebben will you test this? https://github.com/ryanpcmcquen/scrollEvents/blob/breakPoint_test/scrollEvents.js

**Comment by RamonGebben** [comment]
Yes  I will :)

**Comment by ryanpcmcquen** [comment]
Thank you @RamonGebben! I just rebased it on to gh-pages, so you can also benefit from the improved throttle function. :tada:

**Comment by RamonGebben** [comment]
doesnt seem to work for me http://codepen.io/anon/pen/MaopBd

**Comment by Tarabyte** [comment]
@RamonGebben 
- Initial value was not specified `changeStyle('.foo', 'height', '*200px*', '400px', '.bar')`
- And `.bar`'s offsetTop was too high.

http://codepen.io/anon/pen/mewLwR

**Comment by RamonGebben** [comment]
Why would it be to high? 

Updated you fork like this http://codepen.io/anon/pen/pjwVxG

I want to be able to set any element as a thershold no matter what the offset would be.

**Comment by Tarabyte** [comment]
Sure you can set any element as a threshold. But some thresholds are unreachable. You simply can't scroll the amount (`window.pageYOffset` will allways be less than `document.querySelector('.bar').offsetTop`)

**Comment by ryanpcmcquen** [comment]
Since it does work in @Tarabyte's example, I have merged it into `gh-pages`.

https://jsfiddle.net/ryanpcmcquen/c2Lyqzvp/

**Comment by ryanpcmcquen** [comment]
@RamonGebben there are a couple ways you could accomplish what you want in your example, one way is to have a hidden css element that is near the top of the page when the viewport is at the very bottom:

https://jsfiddle.net/ryanpcmcquen/wszo2he5/

**Comment by ryanpcmcquen** [comment]
That last way I posted is pretty awful though, and won't be reliable across different screen sizes. A _much_ better way is to place an element the viewport height from the bottom.

Your JavaScript should look like this:

```
var viewportHeight = Math.max(document.documentElement.clientHeight, window.innerHeight || 0);
document.querySelector('.hidden-thing').style.bottom = viewportHeight + "px";
scrollEvents.changeStyle(".foo", "height", "200px", "400px", ".hidden-thing");
```

Here is a live demo that seems to work: 
https://jsfiddle.net/ryanpcmcquen/y4htmwx4/

Note that you need to set the `style.bottom` before calling `scrollEvents`. :+1:

**Comment by ryanpcmcquen** [comment]
@RamonGebben, any feedback on that last solution?

**Comment by RamonGebben** [comment]
It seems to be working. Good job :)

**Comment by ryanpcmcquen** [comment]
@RamonGebben, I guess the question now is, does that close the issue, or should the library handle selector breakPoints differently?

Personally I like the way it works now, because making it work when an element enters the viewport would probably mean creating some kind of shadow element. That sounds precarious and a bit more complex than I would like. I _do_ think we should mention this example in the README though. Thoughts?

**Comment by RamonGebben** [comment]
@ryanpcmcquen You should post it as a clear example and describe why it does not work on "viewport enter" but how you could get that effect. Other than that I would say it was closed a few comments ago :)

**Comment by ryanpcmcquen** [comment]
Thanks @RamonGebben! Looking at the code again we could just change this:

```
if(typeof breakPoint === 'string') { //breakPoint is a selector
  breakPoint = doc.querySelector(breakPoint).offsetTop;
}
```

to something like this:

```
if(typeof breakPoint === 'string') { //breakPoint is a selector
  breakPoint = doc.querySelector(breakPoint).offsetTop +(Math.max(document.documentElement.clientHeight, window.innerHeight || 0));
}
```

Which one is more intuitive? I guess documenting a workaround on the README is probably the best bet, unless most users prefer things happening when an element enters the viewport.

**Comment by RamonGebben** [comment]
I would not know what other users might prefer. It was the obvious usecase that came to my mind. The fact that it's so light and could be used instead of fancy and bloaded scroller libraries such as [ScrollMagic](http://scrollmagic.io/) is a very cool thing, But that's just one guy's opinion.

**Comment by ryanpcmcquen** [comment]
@RamonGebben thanks, I always like to write lightweight stuff (Unix philosophy FTW). @Tarabyte any feedback on this, should we change the default behavior? I am not opposed to doing that at all, whatever is the most intuitive for users ...

**Comment by ryanpcmcquen** [comment]
@RamonGebben take a look at the [1.0.0 release](https://github.com/ryanpcmcquen/scrollEvents/releases/tag/1.0.0). We changed the way selectors work as the `breakPoint`.

Thanks for your feedback!
