### ISSUE TITLE
Throttle scroll event listener

### ISSUE THREAD

**Issue by ryanpcmcquen** [ryanpcmcquen/scrollEvents#4]
Firing on all scroll events is a bad idea performance wise.

https://viget.com/extend/better-scroll-and-resize-event-handling
http://stackoverflow.com/questions/9613594/scroll-event-firing-too-many-times-i-only-want-it-to-fire-a-maximum-of-say-on

**Comment by mrmartineau** [comment]
Good idea, try https://www.npmjs.com/package/throttleit or https://www.npmjs.com/package/debounce from the [component library](http://github.com/component)

**Comment by ryanpcmcquen** [comment]
Should be fixed now: https://github.com/ryanpcmcquen/scrollEvents/commit/57315416113628031522d84360563d456aadc104

**Comment by ryanpcmcquen** [comment]
This is even better now, using a simplified version of https://github.com/jashkenas/underscore throttle.

https://github.com/ryanpcmcquen/scrollEvents/commit/c544d4e06f11f46313491f80c182c8daaccea15f
